name: Execute Python Script

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Execute Python script
        run: |
          python script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-result_A
          path: fichier_from_script_A.txt
          retention-days: 30
